openapi: 3.0.0
info:
  title: API Gateway
  description: API Gateway là điểm truy cập trung tâm của hệ thống, chịu trách nhiệm định tuyến các yêu cầu đến các microservices phù hợp
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Máy chủ phát triển cục bộ
paths:
  /api/orders:
    post:
      summary: Tạo đơn hàng mới
      description: Chuyển tiếp yêu cầu đến Order Service để tạo đơn hàng mới
      requestBody:
        description: Thông tin đơn hàng cần tạo
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Đơn hàng được tạo thành công
          content:
            application/json:
              schema:
                type: object
        '400':
          description: Dữ liệu không hợp lệ
        '500':
          description: Lỗi máy chủ
  /api/orders/{id}:
    get:
      summary: Lấy thông tin đơn hàng
      description: Chuyển tiếp yêu cầu đến Order Service để lấy thông tin đơn hàng theo ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID của đơn hàng
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Thao tác thành công
          content:
            application/json:
              schema:
                type: object
        '404':
          description: Không tìm thấy đơn hàng
        '500':
          description: Lỗi máy chủ
  /api/products:
    get:
      summary: Lấy danh sách sản phẩm
      description: Chuyển tiếp yêu cầu đến Product Service để lấy danh sách sản phẩm
      parameters:
        - name: page
          in: query
          description: Số trang
          schema:
            type: integer
        - name: size
          in: query
          description: Số lượng sản phẩm trên mỗi trang
          schema:
            type: integer
      responses:
        '200':
          description: Thao tác thành công
          content:
            application/json:
              schema:
                type: object
        '500':
          description: Lỗi máy chủ
  /api/products/{id}:
    get:
      summary: Lấy thông tin chi tiết sản phẩm
      description: Chuyển tiếp yêu cầu đến Product Service để lấy thông tin chi tiết sản phẩm
      parameters:
        - name: id
          in: path
          required: true
          description: ID của sản phẩm
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Thao tác thành công
          content:
            application/json:
              schema:
                type: object
        '404':
          description: Không tìm thấy sản phẩm
        '500':
          description: Lỗi máy chủ
  /api/users/{username}:
    get:
      summary: Lấy thông tin người dùng
      description: Chuyển tiếp yêu cầu đến User Service để lấy thông tin người dùng
      parameters:
        - name: username
          in: path
          required: true
          description: Tên đăng nhập của người dùng
          schema:
            type: string
      responses:
        '200':
          description: Thao tác thành công
          content:
            application/json:
              schema:
                type: object
        '404':
          description: Không tìm thấy người dùng
        '500':
          description: Lỗi máy chủ
  /api/cart/{username}/items:
    get:
      summary: Lấy giỏ hàng của người dùng
      description: Chuyển tiếp yêu cầu đến Cart Service để lấy giỏ hàng của người dùng
      parameters:
        - name: username
          in: path
          required: true
          description: Tên đăng nhập của người dùng
          schema:
            type: string
      responses:
        '200':
          description: Thao tác thành công
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
        '404':
          description: Không tìm thấy người dùng hoặc giỏ hàng
        '500':
          description: Lỗi máy chủ
  /api/notifications/email:
    post:
      summary: Gửi email thông báo
      description: Chuyển tiếp yêu cầu đến Notification Service để gửi email thông báo
      requestBody:
        description: Thông tin email cần gửi
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Email được gửi thành công
          content:
            application/json:
              schema:
                type: object
        '400':
          description: Dữ liệu không hợp lệ
        '500':
          description: Lỗi máy chủ
components:
  schemas:
    RouteDefinition:
      type: object
      properties:
        id:
          type: string
          description: ID của route
        predicates:
          type: array
          description: Các quy tắc xác định yêu cầu sẽ đi theo route này
          items:
            type: object
            properties:
              name:
                type: string
              args:
                type: object
        filters:
          type: array
          description: Các bộ lọc áp dụng cho yêu cầu
          items:
            type: object
            properties:
              name:
                type: string
              args:
                type: object
        uri:
          type: string
          description: URI đích
        order:
          type: integer
          description: Thứ tự ưu tiên của route 