openapi: 3.0.0
info:
  title: Order Service API
  description: API quản lý toàn bộ quá trình đặt hàng, từ tạo đơn hàng đến kiểm tra tính hợp lệ và lưu trữ thông tin
  version: 1.0.0
servers:
  - url: http://localhost:8081
    description: Máy chủ phát triển cục bộ
paths:
  /api/orders:
    post:
      summary: Tạo đơn hàng mới
      description: Tạo đơn hàng mới với thông tin chi tiết được cung cấp
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderRequest'
      responses:
        '201':
          description: Đơn hàng được tạo thành công
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '400':
          description: Dữ liệu không hợp lệ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Lỗi máy chủ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/orders/{id}:
    get:
      summary: Lấy thông tin đơn hàng theo ID
      description: Trả về thông tin chi tiết của đơn hàng theo ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID của đơn hàng
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Thao tác thành công
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '404':
          description: Không tìm thấy đơn hàng
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Lỗi máy chủ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/orders/user/{username}:
    get:
      summary: Lấy danh sách đơn hàng của người dùng
      description: Trả về danh sách tất cả đơn hàng của một người dùng cụ thể
      parameters:
        - name: username
          in: path
          required: true
          description: Tên đăng nhập của người dùng
          schema:
            type: string
      responses:
        '200':
          description: Thao tác thành công
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
        '404':
          description: Không tìm thấy người dùng
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Lỗi máy chủ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/orders/{id}/status:
    put:
      summary: Cập nhật trạng thái đơn hàng
      description: Cập nhật trạng thái của đơn hàng (PENDING, CONFIRMED, SHIPPED, DELIVERED, CANCELLED)
      parameters:
        - name: id
          in: path
          required: true
          description: ID của đơn hàng
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - status
              properties:
                status:
                  type: string
                  description: Trạng thái mới của đơn hàng
                  enum: [PENDING, CONFIRMED, SHIPPED, DELIVERED, CANCELLED]
      responses:
        '200':
          description: Trạng thái được cập nhật thành công
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '400':
          description: Dữ liệu không hợp lệ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Không tìm thấy đơn hàng
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Lỗi máy chủ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    OrderRequest:
      type: object
      required:
        - customerUsername
        - deliveryDate
        - shippingAddress
        - items
      properties:
        customerUsername:
          type: string
          description: Tên đăng nhập của khách hàng
        customerName:
          type: string
          description: Tên của khách hàng
        customerEmail:
          type: string
          format: email
          description: Email của khách hàng
        customerPhone:
          type: string
          description: Số điện thoại của khách hàng
        deliveryDate:
          type: string
          format: date-time
          description: Ngày giao hàng yêu cầu (phải sau ít nhất 2 ngày kể từ hiện tại)
        shippingAddress:
          $ref: '#/components/schemas/ShippingAddress'
        items:
          type: array
          description: Các sản phẩm trong đơn hàng
          items:
            $ref: '#/components/schemas/OrderItemRequest'
    OrderItemRequest:
      type: object
      required:
        - shoeId
        - size
        - color
        - quantity
      properties:
        shoeId:
          type: integer
          format: int64
          description: ID của giày
        size:
          type: number
          format: double
          description: Kích cỡ giày
        color:
          type: string
          description: Màu sắc giày
        quantity:
          type: integer
          description: Số lượng
    Order:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: ID của đơn hàng
        customerUsername:
          type: string
          description: Tên đăng nhập của khách hàng
        totalPrice:
          type: number
          format: double
          description: Tổng giá trị đơn hàng
        deliveryDate:
          type: string
          format: date-time
          description: Ngày giao hàng
        shippingAddress:
          $ref: '#/components/schemas/ShippingAddress'
        status:
          type: string
          description: Trạng thái đơn hàng (PENDING, CONFIRMED, SHIPPED, DELIVERED, CANCELLED)
          enum: [PENDING, CONFIRMED, SHIPPED, DELIVERED, CANCELLED]
        createdAt:
          type: string
          format: date-time
          description: Thời gian tạo
        updatedAt:
          type: string
          format: date-time
          description: Thời gian cập nhật gần nhất
        items:
          type: array
          description: Các sản phẩm trong đơn hàng
          items:
            $ref: '#/components/schemas/OrderItem'
    OrderItem:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: ID của chi tiết đơn hàng
        orderId:
          type: integer
          format: int64
          description: ID của đơn hàng
        shoeId:
          type: integer
          format: int64
          description: ID của giày
        size:
          type: number
          format: double
          description: Kích cỡ giày
        color:
          type: string
          description: Màu sắc giày
        quantity:
          type: integer
          description: Số lượng
        unitPrice:
          type: number
          format: double
          description: Giá trên mỗi đơn vị
        shoeName:
          type: string
          description: Tên giày
        imageUrl:
          type: string
          description: URL hình ảnh giày
    ShippingAddress:
      type: object
      required:
        - recipientName
        - phone
        - province
        - district
        - ward
        - detail
      properties:
        recipientName:
          type: string
          description: Tên người nhận
        phone:
          type: string
          description: Số điện thoại liên hệ
        province:
          type: string
          description: Tỉnh/Thành phố
        district:
          type: string
          description: Quận/Huyện
        ward:
          type: string
          description: Phường/Xã
        detail:
          type: string
          description: Địa chỉ chi tiết
    Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
          description: Mã lỗi
        message:
          type: string
          description: Thông báo lỗi 