openapi: 3.0.0
info:
  title: Product Service API
  description: API quản lý sản phẩm và kiểm tra tồn kho trong hệ thống đặt hàng trực tuyến
  version: 1.0.0
servers:
  - url: http://localhost:8082
    description: Máy chủ phát triển cục bộ
paths:
  /api/products:
    get:
      summary: Lấy danh sách sản phẩm
      description: Trả về danh sách tất cả các sản phẩm có sẵn
      parameters:
        - name: page
          in: query
          description: Số trang (bắt đầu từ 0)
          schema:
            type: integer
            default: 0
        - name: size
          in: query
          description: Số lượng sản phẩm trên mỗi trang
          schema:
            type: integer
            default: 10
      responses:
        '200':
          description: Thao tác thành công
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    type: array
                    items:
                      $ref: '#/components/schemas/Product'
                  totalElements:
                    type: integer
                  totalPages:
                    type: integer
                  size:
                    type: integer
                  number:
                    type: integer
        '500':
          description: Lỗi máy chủ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/products/{id}:
    get:
      summary: Lấy thông tin chi tiết sản phẩm
      description: Trả về thông tin chi tiết của một sản phẩm theo ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID của sản phẩm
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Thao tác thành công
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Không tìm thấy sản phẩm
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Lỗi máy chủ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/products/check:
    get:
      summary: Kiểm tra tồn kho
      description: Kiểm tra số lượng tồn kho của sản phẩm
      parameters:
        - name: productId
          in: query
          required: true
          description: ID của sản phẩm
          schema:
            type: integer
            format: int64
        - name: quantity
          in: query
          required: true
          description: Số lượng cần kiểm tra
          schema:
            type: integer
      responses:
        '200':
          description: Thao tác thành công
          content:
            application/json:
              schema:
                type: object
                properties:
                  available:
                    type: boolean
                    description: Tồn kho đủ số lượng yêu cầu hay không
                  currentStock:
                    type: integer
                    description: Số lượng tồn kho hiện tại
        '404':
          description: Không tìm thấy sản phẩm
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Lỗi máy chủ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/products/{id}/updateQuantity:
    put:
      summary: Cập nhật số lượng tồn kho
      description: Cập nhật số lượng tồn kho của sản phẩm
      parameters:
        - name: id
          in: path
          required: true
          description: ID của sản phẩm
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - quantity
              properties:
                quantity:
                  type: integer
                  description: Số lượng cần cập nhật (âm để giảm, dương để tăng)
      responses:
        '200':
          description: Cập nhật thành công
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '400':
          description: Dữ liệu không hợp lệ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Không tìm thấy sản phẩm
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Lỗi máy chủ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: ID của sản phẩm
        name:
          type: string
          description: Tên sản phẩm
        description:
          type: string
          description: Mô tả sản phẩm
        price:
          type: number
          format: double
          description: Giá sản phẩm
        quantityInStock:
          type: integer
          description: Số lượng tồn kho
    Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
          description: Mã lỗi
        message:
          type: string
          description: Thông báo lỗi 